/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ENVSENSOR_ENVSENSOR_PB_H_INCLUDED
#define PB_ENVSENSOR_ENVSENSOR_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _envsensor_BME280 {
    float t;
    float p;
    float h;
} envsensor_BME280;

typedef struct _envsensor_SHT4X {
    float t;
    float h;
} envsensor_SHT4X;

typedef struct _envsensor_Reading {
    uint64_t mac;
    int32_t rssi; /* dBm (negative); zigzag encoding keeps this small */
    uint32_t batt; /* placeholder for battery voltage in millivolts (will be implemented later) */
    float esp32_t; /* placeholder for ESP32 temperature (will be implemented later) */
    bool has_bme280;
    envsensor_BME280 bme280;
    bool has_sht4x;
    envsensor_SHT4X sht4x;
} envsensor_Reading;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define envsensor_BME280_init_default            {0, 0, 0}
#define envsensor_SHT4X_init_default             {0, 0}
#define envsensor_Reading_init_default           {0, 0, 0, 0, false, envsensor_BME280_init_default, false, envsensor_SHT4X_init_default}
#define envsensor_BME280_init_zero               {0, 0, 0}
#define envsensor_SHT4X_init_zero                {0, 0}
#define envsensor_Reading_init_zero              {0, 0, 0, 0, false, envsensor_BME280_init_zero, false, envsensor_SHT4X_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define envsensor_BME280_t_tag                   1
#define envsensor_BME280_p_tag                   2
#define envsensor_BME280_h_tag                   3
#define envsensor_SHT4X_t_tag                    1
#define envsensor_SHT4X_h_tag                    2
#define envsensor_Reading_mac_tag                1
#define envsensor_Reading_rssi_tag               2
#define envsensor_Reading_batt_tag               3
#define envsensor_Reading_esp32_t_tag            4
#define envsensor_Reading_bme280_tag             5
#define envsensor_Reading_sht4x_tag              6

/* Struct field encoding specification for nanopb */
#define envsensor_BME280_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    t,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    p,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    h,                 3)
#define envsensor_BME280_CALLBACK NULL
#define envsensor_BME280_DEFAULT NULL

#define envsensor_SHT4X_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    t,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    h,                 2)
#define envsensor_SHT4X_CALLBACK NULL
#define envsensor_SHT4X_DEFAULT NULL

#define envsensor_Reading_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED64,  mac,               1) \
X(a, STATIC,   SINGULAR, SINT32,   rssi,              2) \
X(a, STATIC,   SINGULAR, UINT32,   batt,              3) \
X(a, STATIC,   SINGULAR, FLOAT,    esp32_t,           4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  bme280,            5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sht4x,             6)
#define envsensor_Reading_CALLBACK NULL
#define envsensor_Reading_DEFAULT NULL
#define envsensor_Reading_bme280_MSGTYPE envsensor_BME280
#define envsensor_Reading_sht4x_MSGTYPE envsensor_SHT4X

extern const pb_msgdesc_t envsensor_BME280_msg;
extern const pb_msgdesc_t envsensor_SHT4X_msg;
extern const pb_msgdesc_t envsensor_Reading_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define envsensor_BME280_fields &envsensor_BME280_msg
#define envsensor_SHT4X_fields &envsensor_SHT4X_msg
#define envsensor_Reading_fields &envsensor_Reading_msg

/* Maximum encoded size of messages (where known) */
#define ENVSENSOR_ENVSENSOR_PB_H_MAX_SIZE        envsensor_Reading_size
#define envsensor_BME280_size                    15
#define envsensor_Reading_size                   55
#define envsensor_SHT4X_size                     10

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
