/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "envsensor.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(envsensor_BME280, envsensor_BME280, AUTO)


PB_BIND(envsensor_SHT4X, envsensor_SHT4X, AUTO)


PB_BIND(envsensor_Reading, envsensor_Reading, AUTO)



